### ISSUE TITLE
Are you going to release the source code?

### ISSUE THREAD

**Issue by esgnn** [lattas/AvatarMe#1]
Very cool paper.
Do you have any future plans to release it?

**Comment by vitahsu** [comment]
I want to know too.
Thanks!

**Comment by lattas** [comment]
Hi @esgnn and @vitahsu ,
thank you for your interest in our work!
More information about data release will be posted during CVPR 2020.

**Comment by munkim** [comment]
So will it be a data release or source code release?

**Comment by adriendoerig** [comment]
Yes awesome work! I would also like to know if you will release code to produce faces from photos, or just the data used to train your system?

**Comment by JaredS215** [comment]
Are there any public updates post CVPR 2020?

**Comment by lattas** [comment]
Hi all and thank you for your interest in our work! We will be releasing reflectance patches that we used in our training, as described in the paper. Due to their sensitive nature, they are anonymized (i.e., the patches cannot be traced back to the individuals they belong to) and will only be provided for academic research purposes. Imperial College London is still in lockdown, which has delayed the release process. We will update you on this page as soon as possible.

**Comment by jgwinner** [comment]
Thank you!

Would there be any possibility of a seed funding VR startup to obtain commercial release of data or code? (We do have funding, but not much. It wouldn't be pubically posted!)

        == John ==

**Comment by lattas** [comment]
Dear all, you can now obtain the public dataset. There are no plans at the moment to release code with trained models. For the dataset, please send us an email, following the updated instructions on the main [README](https://github.com/lattas/AvatarMe/blob/master/README.md#public-dataset) page.
