### ISSUE TITLE
When will you release the dataset?

### ISSUE THREAD

**Issue by yhw-yhw** [lattas/AvatarMe#3]
Interesting work. I wonder to know when you will release the dataset?

**Comment by test1230-lab** [comment]
Is it not in a working state now?

**Comment by lattas** [comment]
We are planning to release the dataset, but due to the COVID-19 lockdown of Imperial College London and the nature of the data, the procedure has taken longer than we expected. We will post updates on this github page. Please note that data will only be provided to accredited research institutions for research and educations purposes only.

**Comment by pranavpandey2511** [comment]
Is there any update on the dataset?

**Comment by MandyMo** [comment]
My god, the CVPR 2021 is approaching, while the dataset stills remains a mistery.

**Comment by lattas** [comment]
We profusely apologise for the delay in the release of the dataset. There have been issues beyond our control (especially since the College effectively closed down in March due to Covid), but we are aiming at releasing the data before Christmas. It is in our interest to release the dataset and thus increase the impact of our work and we’re doing everything we can to achieve this as soon as possible. Thank you for your interest in our work.

**Comment by lattas** [comment]
Dear all, you can now obtain the public dataset. Thank you for you patience. Please send us an email, following the updated instructions on the main [README](https://github.com/lattas/AvatarMe/blob/master/README.md#public-dataset) page.
